name: release dc

on:
  push:
    tags:
      - 'dc-v**'
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [linux, darwin, windows]
    env:
      GOARCH: amd64
      GOOS: ${{ matrix.os }}
    name: release
    runs-on: ubuntu-latest
    outputs:
      sha_linux: ${{ steps.shasum.outputs.sha_linux }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      # - run: go test ./dc/tests
      #   env:
      #     GOOS: linux
      - run: go test ./common/**/tests
        env:
          GOOS: linux
      - run: .github/package-artifacts.sh
        env:
          BINARY_NAME: dc
          BUILD_DIR: dc
          GITHUB_REF: ${{ github.ref }}
          GOOS: ${{ matrix.os }}
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "artifacts/*{.tar.gz,.sha256}"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
