name: test tf

on:
  push:
    branches:
      - main
    paths:
      - tf/**
      - common/**
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - tf/**
      - common/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - run: go test ./tf/tests
      - run: go test ./common/**/tests
